"""添加了采购单备注和打包入库异常留言的时间

Revision ID: 3659777be057
Revises: a6ce3ea02e41
Create Date: 2025-01-07 11:03:11.753049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3659777be057'
down_revision = 'a6ce3ea02e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packer_msg_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mark', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('mark')
        batch_op.drop_column('packer_msg_date')

    # ### end Alembic commands ###
