"""initDatabase

Revision ID: 7ef8a6fdca2c
Revises: 
Create Date: 2024-06-04 14:53:40.796561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef8a6fdca2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('passward', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telephone_number', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('power_arange', sa.Text(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('machining_cutter',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('mark', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machining_device',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('mark', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machining_kinematic_pair',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('mark', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machining_machining_features',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('mark', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machining_material',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('mark', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machining_process_parameters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('mark', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machining_size_parameters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('mark', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machining_kinematic_pairs_process_parameters',
    sa.Column('machining_kinematic_pair_id', sa.Text(), nullable=False),
    sa.Column('machining_process_parameters_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['machining_kinematic_pair_id'], ['machining_kinematic_pair.id'], ),
    sa.ForeignKeyConstraint(['machining_process_parameters_id'], ['machining_process_parameters.id'], ),
    sa.PrimaryKeyConstraint('machining_kinematic_pair_id', 'machining_process_parameters_id')
    )
    op.create_table('machining_machining_features_size_parameters',
    sa.Column('machining_machining_features_id', sa.Text(), nullable=False),
    sa.Column('machining_size_parameters_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['machining_machining_features_id'], ['machining_machining_features.id'], ),
    sa.ForeignKeyConstraint(['machining_size_parameters_id'], ['machining_size_parameters.id'], ),
    sa.PrimaryKeyConstraint('machining_machining_features_id', 'machining_size_parameters_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machining_machining_features_size_parameters')
    op.drop_table('machining_kinematic_pairs_process_parameters')
    op.drop_table('machining_size_parameters')
    op.drop_table('machining_process_parameters')
    op.drop_table('machining_material')
    op.drop_table('machining_machining_features')
    op.drop_table('machining_kinematic_pair')
    op.drop_table('machining_device')
    op.drop_table('machining_cutter')
    op.drop_table('user')
    # ### end Alembic commands ###
