"""增加采购单 数量列

Revision ID: 928b42b6d75d
Revises: 7398d1ce2016
Create Date: 2024-11-14 13:35:54.517705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928b42b6d75d'
down_revision = '7398d1ce2016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
