"""采购单 新增国内运单号

Revision ID: cb761f5afd3a
Revises: 928b42b6d75d
Create Date: 2024-11-14 16:48:57.363274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb761f5afd3a'
down_revision = '928b42b6d75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('posting_numbers', sa.Text(), nullable=True))
        batch_op.drop_column('posting_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posting_number', sa.TEXT(), nullable=True))
        batch_op.drop_column('posting_numbers')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
