"""addCatalog

Revision ID: d26c3f086b29
Revises: 7ef8a6fdca2c
Create Date: 2024-06-05 08:37:56.864492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26c3f086b29'
down_revision = '7ef8a6fdca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machining_cutter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_address', sa.Text(), nullable=True))

    with op.batch_alter_table('machining_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_address', sa.Text(), nullable=True))

    with op.batch_alter_table('machining_kinematic_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_address', sa.Text(), nullable=True))

    with op.batch_alter_table('machining_machining_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_address', sa.Text(), nullable=True))

    with op.batch_alter_table('machining_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_address', sa.Text(), nullable=True))

    with op.batch_alter_table('machining_process_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_address', sa.Text(), nullable=True))

    with op.batch_alter_table('machining_size_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machining_size_parameters', schema=None) as batch_op:
        batch_op.drop_column('pic_address')

    with op.batch_alter_table('machining_process_parameters', schema=None) as batch_op:
        batch_op.drop_column('pic_address')

    with op.batch_alter_table('machining_material', schema=None) as batch_op:
        batch_op.drop_column('pic_address')

    with op.batch_alter_table('machining_machining_features', schema=None) as batch_op:
        batch_op.drop_column('pic_address')

    with op.batch_alter_table('machining_kinematic_pair', schema=None) as batch_op:
        batch_op.drop_column('pic_address')

    with op.batch_alter_table('machining_device', schema=None) as batch_op:
        batch_op.drop_column('pic_address')

    with op.batch_alter_table('machining_cutter', schema=None) as batch_op:
        batch_op.drop_column('pic_address')

    # ### end Alembic commands ###
