"""2024.12.31 数据库调整

Revision ID: a6ce3ea02e41
Revises: 7cc3555fad27
Create Date: 2024-12-31 10:06:10.629664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ce3ea02e41'
down_revision = '7cc3555fad27'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchaser_id', sa.Text(), nullable=True))
        batch_op.create_foreign_key('user_purchaser_id', 'user', ['purchaser_id'], ['id'])

    with op.batch_alter_table('purchase_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_in_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stock_out_id', sa.Text(), nullable=True))
        batch_op.create_foreign_key('user_stock_in_id', 'user', ['stock_in_id'], ['id'])
        batch_op.create_foreign_key('user_stock_out_id', 'user', ['stock_out_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_product', schema=None) as batch_op:
        batch_op.drop_constraint('user_stock_in_id', type_='foreignkey')
        batch_op.drop_constraint('user_stock_out_id', type_='foreignkey')
        batch_op.drop_column('stock_out_id')
        batch_op.drop_column('stock_in_id')

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint('user_purchaser_id', type_='foreignkey')
        batch_op.drop_column('purchaser_id')

    # ### end Alembic commands ###
